#!/usr/bin/env bash

wget -c $TRACKERLIST_ALL
wget -c $TRACKERLIST_ALL_HTTP
wget -c $TRACKERLIST_ALL_HTTPS
wget -c $TRACKERLIST_ALL_I2P
wget -c $TRACKERLIST_ALL_IP
wget -c $TRACKERLIST_ALL_UDP
wget -c $TRACKERLIST_ALL_WS
wget -c $TRACKERLIST_BEST
wget -c $TRACKERLIST_BEST_IP
wget -c $TRACKERLIST_BLACKLIST

rm -rf *.txt.*
